In [2]:

# demonstrate the types of features created
from numpy import asarray
from sklearn.preprocessing import PolynomialFeatures # define the dataset
data = asarray([[2,3], [2,3], [2,3]])
print(data)
# perform a polynomial features transform of the dataset 
trans = PolynomialFeatures(degree=2)
data=trans.fit_transform(data)
print(data)
#(x1,x2)->degree=2->1,x1,x2,×1*x1,x1*x2,×2*x2 I
#(x1,x2)->degree=3->1,x1,x2,x1*x1,x1*x2,x2*x2,x1*x1*x1,x1*x1*x2,x1*x2*x2,x2*x*x2
#degreeint or tuple (min_degree, max_degree), default=2
#interaction_onlybool, default=False
#include_biasbool, default=True
#Ref:https://letsdatascience.com/polynomial-features/

[[2 3]
 [2 3]
 [2 3]]
[[1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]]


In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df=pd.read_csv('profit.csv')
print(df)

       gold  estate    cryto  stock  profit
0     14.96   41.76  1024.07  73.17  463.26
1     25.18   62.96  1020.04  59.08  444.37
2      5.11   39.40  1012.16  92.14  488.56
3     20.86   57.32  1010.24  76.64  446.48
4     10.82   37.50  1009.23  96.62  473.90
...     ...     ...      ...    ...     ...
9563  16.65   49.69  1014.01  91.00  460.03
9564  13.19   39.18  1023.67  66.78  469.62
9565  31.32   74.33  1012.92  36.48  429.57
9566  24.48   69.45  1013.86  62.39  435.74
9567  21.60   62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   gold    9568 non-null   float64
 1   estate  9568 non-null   float64
 2   cryto   9568 non-null   float64
 3   stock   9568 non-null   float64
 4   profit  9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [6]:
x= df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:

from sklearn.preprocessing import PolynomialFeatures 
poly_fe = PolynomialFeatures(degree=4) 
poly_data = poly_fe.fit_transform(x) 
X_poly = pd.DataFrame(data=poly_data)
print (X_poly)


       0      1      2        3      4         5          6           7   \
0     1.0  14.96  41.76  1024.07  73.17  223.8016   624.7296  15320.0872   
1     1.0  25.18  62.96  1020.04  59.08  634.0324  1585.3328  25684.6072   
2     1.0   5.11  39.40  1012.16  92.14   26.1121   201.3340   5172.1376   
3     1.0  20.86  57.32  1010.24  76.64  435.1396  1195.6952  21073.6064   
4     1.0  10.82  37.50  1009.23  96.62  117.0724   405.7500  10919.8686   
...   ...    ...    ...      ...    ...       ...        ...         ...   
9563  1.0  16.65  49.69  1014.01  91.00  277.2225   827.3385  16883.2665   
9564  1.0  13.19  39.18  1023.67  66.78  173.9761   516.7842  13502.2073   
9565  1.0  31.32  74.33  1012.92  36.48  980.9424  2328.0156  31724.6544   
9566  1.0  24.48  69.45  1013.86  62.39  599.2704  1700.1360  24819.2928   
9567  1.0  21.60  62.52  1017.23  67.87  466.5600  1350.4320  21972.1680   

             8          9   ...            60            61            62  \
0     1094

In [9]:

from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
scaled_data=mm_scaler.fit_transform(X_poly)
X_scaled = pd.DataFrame(data=scaled_data, columns=X_poly.columns)
print(X_scaled)

       0         1         2         3         4         5         6   \
0     0.0  0.372521  0.291815  0.771591  0.638204  0.160513  0.208762   
1     0.0  0.662040  0.669039  0.671863  0.449330  0.459107  0.571150   
2     0.0  0.093484  0.249822  0.476862  0.892493  0.016622  0.049036   
3     0.0  0.539660  0.568683  0.429349  0.684718  0.314340  0.424159   
4     0.0  0.255241  0.216014  0.404355  0.952547  0.082829  0.126152   
...   ...       ...       ...       ...       ...       ...       ...   
9563  0.0  0.420397  0.432918  0.522643  0.877212  0.199397  0.285197   
9564  0.0  0.322380  0.245907  0.761693  0.552547  0.124247  0.168040   
9565  0.0  0.835977  0.871352  0.495669  0.146381  0.711612  0.851327   
9566  0.0  0.642210  0.784520  0.518931  0.493700  0.433805  0.614460   
9567  0.0  0.560623  0.661210  0.602326  0.567158  0.337209  0.482534   

            7         8         9   ...        60        61        62  \
0     0.379381  0.380802  0.183189  ...  0.137084 

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X_scaled, y, test_size=0.25, random_state=42)


In [11]:
from sklearn.linear_model import LinearRegression 
regressor= LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [12]:
print(regressor.intercept_)
print(regressor.coef_)

282.8450512208454
[-6.61293785e-03  1.59650885e+06  2.88156340e+06 -4.26257564e+06
 -1.88206543e+06 -3.28066774e+05 -5.11710378e+05 -4.13067971e+06
 -1.15781067e+05  5.79544147e+05 -8.74049791e+06 -2.88070508e+05
  1.28176813e+07  5.64373595e+06  1.88478248e+05 -6.74318458e+03
  6.43973698e+04  6.26796834e+05 -3.85709637e+03 -2.51885137e+04
  9.33485057e+05  4.39961126e+04  3.51732519e+06  2.31640956e+05
 -1.29285038e+04 -1.22726198e+04 -1.09951023e+06 -1.03483756e+04
  8.84218776e+06  5.21642500e+05  2.51335614e+04 -1.28492364e+07
 -5.64377806e+06 -3.70297591e+05 -6.66399546e+03 -3.33724087e+02
  4.28092107e+02  6.99153080e+03 -4.64760184e+01 -1.02018577e+03
 -6.28054960e+04 -5.76090950e+01 -2.99280230e+05  3.64391003e+03
  7.63484197e+01  4.77961915e+02  2.55377812e+04 -6.92491128e+02
 -4.23779748e+05 -4.25332732e+04  3.14790326e+01 -9.82576680e+05
 -1.15454932e+05  1.18824381e+04  3.47444451e+02 -2.08168281e+01
  1.22302231e+04  1.50464929e+02  5.19863037e+05  1.08048597e+04
 -3.676

In [13]:
print('Score or R-Squared:', regressor.score(X_train, y_train))

Score or R-Squared: 0.9430236062681677


In [14]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print(y_pred)

[455.98 437.51 434.46 ... 456.81 471.89 448.35]


In [15]:

import numpy as np
from sklearn import metrics
y_test_pred = regressor.predict(X_test)
print('Score or R-Squared:', regressor.score (X_test, y_test))
print('Mean Absolute Error:',
    metrics.mean_absolute_error(y_test, y_test_pred))
print('Root Mean Squared Error:',
    np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error:',
    metrics.mean_absolute_percentage_error(y_test, y_test_pred))

Score or R-Squared: 0.9417558393103492
Mean Absolute Error: 3.163041328713897
Root Mean Squared Error: 4.114666879425069
Mean Absolute Percentage Error: 0.006968453853330015


In [16]:
from sklearn.model_selection import GridSearchCV
model = LinearRegression()
param_space = {'copy_X': [True, False], 'fit_intercept': [True, False], 
               'n_jobs': [1,5,10,15,None], 'positive': [True, False]}

grid_search= GridSearchCV(model, param_space,cv=5)
grid_search.fit(X_train, y_train)

# Parameter which gives the best results
print (f"Best Hyperparameters: {grid_search.best_params_}")
# Accuracy of the model after using best parameters 
print (f"Best Score: {grid_search.best_score_}")

Best Hyperparameters: {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}
Best Score: 0.9416722510809157


In [17]:
bestModel=LinearRegression()
bestModel.set_params (copy_X=True, fit_intercept=True,n_jobs=1, positive=False)
bestModel.fit(X_train,y_train)
print('Score or R-Squared on training dataset:', bestModel.score (X_train, y_train))
y_test_pred = bestModel.predict(X_test)
print('Score or R-Squared on test dataset:', bestModel.score (X_test, y_test))
print('Mean Absolute Error:',
    metrics.mean_absolute_error(y_test, y_test_pred))
print('Root Mean Squared Error:',
    np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error:',
    metrics.mean_absolute_percentage_error(y_test, y_test_pred))

Score or R-Squared on training dataset: 0.9430236062681677
Score or R-Squared on test dataset: 0.9417558393103492
Mean Absolute Error: 3.163041328713897
Root Mean Squared Error: 4.114666879425069
Mean Absolute Percentage Error: 0.006968453853330015


In [18]:

# Xây dựng ứng dụng dự báo profit
#xgold=15.82 
#xestate=47.50
#xcryto=1007
#xstock=100.62
xgold=float(input())
xestate=float(input())
xcryto=float(input())
xstock=float(input())
scaled_value=poly_fe.transform([[xgold, xestate,xcryto,xstock]])
print(scaled_value)
scaled_value=mm_scaler.transform(scaled_value)
print(scaled_value)
predicted_value = bestModel.predict(scaled_value)
print("Predicted profit: ", predicted_value)

[[1.00e+00 1.58e+01 4.75e+01 1.01e+03 1.01e+02 2.50e+02 7.51e+02 1.59e+04
  1.59e+03 2.26e+03 4.78e+04 4.78e+03 1.01e+06 1.01e+05 1.01e+04 3.96e+03
  1.19e+04 2.52e+05 2.52e+04 3.57e+04 7.57e+05 7.56e+04 1.60e+07 1.60e+06
  1.60e+05 1.07e+05 2.27e+06 2.27e+05 4.82e+07 4.81e+06 4.81e+05 1.02e+09
  1.02e+08 1.02e+07 1.02e+06 6.26e+04 1.88e+05 3.99e+06 3.98e+05 5.65e+05
  1.20e+07 1.20e+06 2.54e+08 2.54e+07 2.53e+06 1.70e+06 3.59e+07 3.59e+06
  7.62e+08 7.61e+07 7.61e+06 1.62e+10 1.61e+09 1.61e+08 1.61e+07 5.09e+06
  1.08e+08 1.08e+07 2.29e+09 2.29e+08 2.28e+07 4.85e+10 4.85e+09 4.84e+08
  4.84e+07 1.03e+12 1.03e+11 1.03e+10 1.03e+09 1.03e+08]]
[[0.   0.4  0.39 0.35 1.01 0.18 0.26 0.4  0.58 0.27 0.39 0.55 0.34 0.99
  1.01 0.08 0.12 0.18 0.32 0.15 0.26 0.35 0.4  0.58 0.59 0.17 0.27 0.33
  0.39 0.55 0.64 0.34 0.97 1.   1.01 0.03 0.05 0.08 0.15 0.08 0.12 0.2
  0.18 0.32 0.36 0.09 0.15 0.21 0.25 0.35 0.37 0.4  0.58 0.59 0.61 0.11
  0.17 0.21 0.27 0.33 0.38 0.39 0.55 0.64 0.67 0.34 0.94 0.98 1

c:\Users\HKP\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
